import { useState } from "react";
import API_URL from "../../config/api";
const clinicalFields = [["clinical_pef_max","PEF maximum","Highest peak-flow reading in L/min.","number"],["clinical_pef_morning","Morning PEF","Patient’s morning peak-flow reading in L/min.","number"],["clinical_night_symp","Night symptoms","Whether symptoms were reported overnight.","select"],["clinical_day_symp","Day symptoms","Whether symptoms were reported during the day.","select"],["clinical_limit_activity","Activity limitation","Record the activity-limitation score from the assessment.","number"],["clinical_trigger_count","Trigger count","Number of known triggers recorded for this assessment.","number"]];
const medicationFields = [["med_prev_inhaler","Previous inhaler","Previous or regularly used inhaler count.","number"],["med_relief_inhaler","Relief inhaler","Reliever inhaler count.","number"],["med_inhaler_events","Inhaler events","Number of inhaler-use events recorded.","number"],["med_inhaler_types","Inhaler types","Number of different inhaler types.","number"],["med_n_inhalers","Number of inhalers","Total inhalers currently recorded.","number"]];
export default function PatientDetailsEditor({ patient, onSaved }) {
  const [clinical,setClinical]=useState({...patient.clinical||{}}); const [medication,setMedication]=useState({...patient.medication||{}}); const [message,setMessage]=useState("");
  const calculatedClinical = { clinical_pef_expected_ratio: patient.static_max_pef_expected ? Number(clinical.clinical_pef_max || 0) / Number(patient.static_max_pef_expected) : 0, clinical_pef_best_ratio: patient.static_pef_best ? Number(clinical.clinical_pef_max || 0) / Number(patient.static_pef_best) : 0 };
  const update=(setter,key,value,type)=>setter(current=>({...current,[key]:type==="number"?(value===""?"":Number(value)):value}));
  const save=async()=>{const savedClinical={...clinical,...calculatedClinical};const res=await fetch(`${API_URL}/auth/patients/${patient._id}/details`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("geneair_token")}`},body:JSON.stringify({clinical:savedClinical,medication})});if(!res.ok)return setMessage("Unable to save details");onSaved({clinical:savedClinical,medication});setMessage("Details saved");};
  const render=(fields,values,setter)=>fields.map(([key,label,info,type])=><label className="details-field" key={key}><span>{label}</span><small>{info}</small>{type==="select"?<select value={values[key]??"False"} onChange={e=>update(setter,key,e.target.value,type)}><option value="True">Yes</option><option value="False">No</option></select>:<input type="number" step="any" value={values[key]??""} onChange={e=>update(setter,key,e.target.value,type)}/>}</label>);
  return <div className="patient-details-editor"><div className="details-section-heading"><div><span className="details-eyebrow">PATIENT PLAN</span><h3>Clinical and medication details</h3></div><p>Complete the measured and observed fields. Calculated ratios update automatically.</p></div><section className="details-panel"><h4>Clinical assessment</h4><div className="details-fields-grid">{render(clinicalFields,clinical,setClinical)}</div><div className="calculated-fields"><div><span>Expected PEF ratio</span><strong>{calculatedClinical.clinical_pef_expected_ratio.toFixed(3)}</strong><small>PEF maximum ÷ expected PEF ({patient.static_max_pef_expected || "not set"})</small></div><div><span>Best PEF ratio</span><strong>{calculatedClinical.clinical_pef_best_ratio.toFixed(3)}</strong><small>PEF maximum ÷ patient best PEF ({patient.static_pef_best || "not set"})</small></div></div></section><section className="details-panel"><h4>Medication profile</h4><div className="details-fields-grid">{render(medicationFields,medication,setMedication)}</div></section><div className="details-actions"><button className="doctor-primary-button" type="button" onClick={save}>Save details</button>{message&&<span className="details-save-message">{message}</span>}</div></div>;
}
